version: "3"

services:
  symfony:
    build:
      context: ./symfony
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./symfony:/var/www/symfony

  go:
    build:
      context: ./go
    ports:
      - "8081:8081"

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./symfony:/var/www/symfony
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - symfony
    ports:
      - "80:80"
